server:
  port: 8887
spring:
  application:
    name: cloud-config
  cloud:
    config:
      uri: http://192.168.1.100:8887
#      uri: http://192.168.25.128:8887
      server:
        git:
          uri: https://github.com/yanggy11/cloud-config-repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.100:8761/eureka/
#      defaultZone: http://192.168.25.128:8761/eureka/
security:
  basic:
    enabled: false
management:
#  context-path: /${spring.application.name}
  security:
    enabled: false
