server:
  port: 8887
spring:
  application:
    name: cloud-config
  cloud:
    config:
#      uri: http://192.168.1.100:8887
      uri: http://localhost:8887
      server:
        git:
          uri: https://github.com/yanggy11/cloud-config-repo
  rabbitmq:
    host: 39.107.97.132
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.1.100:8761/eureka/
      defaultZone: http://39.107.97.132:8000/eureka/
security:
  basic:
    enabled: false
management:
#  context-path: /${spring.application.name}
  security:
    enabled: false
